services:
  front:
    image: cesizen-front:latest
    container_name: cesizen-front-dev

    ports:
      - "5175:80"

    env_file:
      - .env

    networks:
      - api_cesizen-api_default

    restart: unless-stopped

networks:
  api_cesizen-api_default:
    external: true


