name: Deploy Front Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-front-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Configurer SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -T 30 -H "$SSH_HOST" >> ~/.ssh/known_hosts || true

      - name: Déployer le Front DEV
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/cesizen-dev/front
            git fetch origin
            git reset --hard origin/dev

            cd ~/cesizen-dev

            docker compose -f docker-compose.dev.yml up -d --build front
          EOF