name: Docker PROD Status

on:
  workflow_dispatch:

jobs:
  check-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Configurer SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Vérifier Docker
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "docker ps | grep cesizen-front-prod"